In [1]:
import pandas as pd
import numpy as np

# Will show the clean build time and the executable's binary size for all system's configurations
path = '/src/data/rez_sample_03ALL/'
df1 = pd.read_csv(path + 'clean-bt.csv', converters={'BranchC': lambda x: str(x)})
df2 = pd.read_csv(path + 'i_data_frame.csv', converters={'Br2': lambda x: str(x)})

df1 = df1.rename(columns = {"BranchC": "Branch", "Build Time": "Clean Build Time"})
df2 = df2.rename(columns = {"Br2": "Branch"})

df2 = pd.DataFrame(data=df2)

pd.set_option("display.max_columns", None)
df2 = df2.set_index("Branch")

df2
#df3 = pd.merge(df1, df2) 
#df3.round(decimals=2)

,00001,00002,00003,00004,00005,00006,00007,00008,00009,00010,00011,00012,00013,00014,00015,00016,00017,00018,00019,00020
Branch,,,,,,,,,,,,,,,,,,,,
00001,NaN,0.2525,0.2095,0.2705,0.0515,0.0525,0.2730,0.0540,0.0535,0.2700,0.2645,0.2165,0.2420,0.2645,0.2600,0.0560,0.2900,0.0520,0.0515,0.2705
00002,20.3420,NaN,37.7785,38.7685,20.1585,20.3935,39.1740,20.9685,20.2495,38.4765,38.4480,38.1680,38.4170,38.4365,38.6145,1.0605,38.8455,20.3120,38.2230,38.8665
00003,0.1060,25.9960,NaN,26.4320,0.1075,0.1075,26.7995,0.1105,0.1065,26.3530,26.2325,26.0725,26.2540,26.3040,26.2555,0.1090,26.3620,0.1075,25.9880,26.4595
00004,20.7975,39.8955,39.6230,NaN,20.6060,20.7470,39.8090,21.1270,21.1095,39.9125,40.0280,39.8190,39.9540,40.1400,40.0960,0.1110,40.0360,20.4270,39.9250,40.1915
00005,0.0615,0.3060,0.2595,0.3200,NaN,0.0620,0.3205,0.0630,0.0600,0.3180,0.3115,0.2635,0.2895,0.3140,0.3080,0.0645,0.3235,0.0615,0.2630,0.3185
00006,1.2285,1.2150,1.2320,1.2245,1.1650,NaN,1.2380,1.2460,1.2465,1.2225,1.2280,1.1775,1.1825,1.2300,1.2235,1.2370,1.2200,1.1720,1.1725,1.2270
00007,0.1170,18.9120,18.6550,19.2220,0.1170,0.1155,NaN,0.1190,0.1195,18.9850,18.8860,18.8995,19.0225,19.1165,18.9695,0.1190,19.0000,0.1160,18.7780,19.2030
00008,0.0545,0.3000,0.2560,0.3155,0.0520,0.0535,0.3155,NaN,0.0555,0.3180,0.3075,0.2620,0.2925,0.3210,0.3010,0.0545,0.3190,0.0520,0.2580,0.3120
00009,0.0615,0.0625,0.0600,0.0640,0.0605,0.0605,0.0615,0.0620,NaN,0.0690,0.0615,0.0605,0.0605,0.0615,0.0615,0.0650,0.0620,0.0600,0.0620,0.0660
00010,0.1060,19.8115,19.6645,19.8180,0.1040,0.1090,19.6130,0.1115,0.1190,NaN,19.7865,19.6630,19.7690,19.8340,19.8435,0.1105,19.8115,0.1080,19.6780,19.9250
00011,26.5555,51.5900,51.1925,52.1185,26.1820,26.5015,51.6025,27.4060,27.5760,51.7935,NaN,51.5350,51.5865,51.7630,51.6710,0.1090,51.8455,26.3825,51.4675,51.9995
00012,1.1185,22.2890,21.9450,22.3385,1.0690,1.0780,22.0465,1.0775,1.1060,22.1650,22.2050,NaN,22.0655,22.2900,22.2330,1.0820,22.1455,1.0730,22.0060,22.3735
00013,19.1725,36.3410,36.3910,37.0930,19.0645,19.1420,36.7480,19.5825,19.1100,36.6895,36.7450,36.6400,NaN,36.7480,36.8390,0.1205,36.8400,19.0555,36.6640,37.1365
00014,34.6790,65.8525,64.6340,65.5755,34.4050,34.4020,65.1115,36.1405,36.0645,65.0860,65.1685,64.5620,65.1700,NaN,65.5680,1.0720,65.2095,34.2820,65.1060,65.7625
00015,19.6780,37.9605,37.0045,38.1385,19.4765,19.8935,37.8260,19.9775,19.9780,37.9015,37.8960,37.7010,37.7690,37.7675,NaN,0.3555,37.9460,19.6155,37.7080,38.2210
00016,21.4560,1.2265,21.3700,1.2545,21.2000,21.2700,21.5715,21.7380,21.6535,21.5575,1.0110,21.4185,1.2150,1.2475,1.2225,NaN,21.6115,21.2380,21.4130,1.2375
00017,0.1155,24.8835,24.6960,25.0460,0.1155,0.1170,24.6760,0.1220,0.1195,24.7680,24.9020,24.7785,24.8790,25.0340,24.8785,0.1190,NaN,0.1170,24.7105,24.9175
00018,0.0535,0.2545,0.2100,0.2595,0.0525,0.0530,0.2735,0.0745,0.0515,0.2710,0.2510,0.2150,0.0515,0.2610,0.2540,0.0540,0.2610,NaN,0.2120,0.2700
00019,1.0760,17.3970,17.2425,17.3510,1.0645,1.0610,17.3225,1.0800,1.1085,17.3810,17.4200,17.3300,17.3470,17.4285,17.4645,1.0600,17.4435,1.0510,NaN,17.5550
00020,28.2280,53.0750,52.3735,52.6625,27.9565,27.9560,52.4350,28.9920,29.2865,52.5200,52.5950,52.3850,52.7410,52.8570,52.7460,1.0770,52.7455,28.0870,52.4750,NaN

In [2]:
# The Minimum build time (col: Min Time) and 
# its corresponding configuration (col: Clean Build) 
# for each incremental build (col: Br2)

tbl1 = df2
tbl1["Clean Build"] = tbl1.idxmin(axis=1)
tbl1["Min Time"] = tbl1.min(axis=1)
tbl2 = tbl1[["Min Time", "Clean Build"]]
tbl2

        Min Time Clean Build
Branch
00001     0.0515       00005
00002     1.0605       00016
00003     0.1060       00001
00004     0.1110       00016
00005     0.0600       00009
00006     1.1650       00005
00007     0.1155       00006
00008     0.0520       00005
00009     0.0600       00003
00010     0.1040       00005
00011     0.1090       00016
00012     1.0690       00005
00013     0.1205       00016
00014     1.0720       00016
00015     0.3555       00016
00016     1.0110       00011
00017     0.1155       00001
00018     0.0515       00009
00019     1.0510       00018
00020     1.0770       00016

In [3]:
tbl3 = tbl1
cols = ['00001', '00002', '00003', '00004', '00005', '00006', '00007', 
        '00008', '00009', '00010', '00011', '00012', '00013', '00014', 
        '00015', '00016', '00017', '00018', '00019', '00020']

tbl3['GreaterThanCB'] = tbl3[cols].gt(37.48).sum(axis=1)
tbl3[["GreaterThanCB"]]

        GreaterThanCB
Branch
00001               0
00002              12
00003               0
00004              12
00005               0
00006               0
00007               0
00008               0
00009               0
00010               0
00011              12
00012               0
00013               0
00014              12
00015              11
00016               0
00017               0
00018               0
00019               0
00020              12